# Generated by Django 5.0.8 on 2024-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('account_no', models.CharField(max_length=10, unique=True)),
                ('mt_version', models.PositiveSmallIntegerField(choices=[(4, 'MT4'), (5, 'MT5')])),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
