# Generated by Django 5.0.8 on 2024-09-03 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('requested_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
